# Generated by Django 4.1.3 on 2022-11-16 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('BLACK', 'BLACK'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW'), ('PURPLE', 'PURPLE'), ('ORANGE', 'ORANGE'), ('RED', 'RED'), ('GREEN', 'GREEN'), ('WHITE', 'WHITE')], default='WHITE', max_length=50)),
                ('border_style', models.CharField(choices=[('SOLID', 'SOLID'), ('DOTTED', 'DOTTED'), ('GROOVE', 'GROOVE'), ('DOUBLE', 'DOUBLE')], default='SOLID', max_length=50)),
                ('border_color', models.CharField(choices=[('BLACK', 'BLACK'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW'), ('PURPLE', 'PURPLE'), ('ORANGE', 'ORANGE'), ('RED', 'RED'), ('GREEN', 'GREEN'), ('WHITE', 'WHITE')], default='BLACK', max_length=50)),
                ('font_family', models.CharField(choices=[('UBUNTO', 'UBUNTO'), ('ARIAL', 'ARIAL'), ('RALEWAY', 'RALEWAY'), ('MERRIWEATHER', 'MERRIWEATHER')], default='UBUNTO', max_length=50)),
                ('font_color', models.CharField(choices=[('BLACK', 'BLACK'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW'), ('PURPLE', 'PURPLE'), ('ORANGE', 'ORANGE'), ('RED', 'RED'), ('GREEN', 'GREEN'), ('WHITE', 'WHITE')], default='BLACK', max_length=50)),
                ('text_alignment', models.CharField(choices=[('CENTER', 'CENTER'), ('LEFT', 'LEFT'), ('RIGHT', 'RIGHT')], default='LEFT', max_length=50)),
                ('outer_msg', models.CharField(max_length=200)),
                ('inner_msg', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('VALENTINES-DAY', 'VALENTINES-DAY'), ('THANK-YOU', 'THANK-YOU'), ('BIRTHDAY', 'BIRTHDAY'), ('CHRISTMAS', 'CHRISTMAS'), ('WEDDING', 'WEDDING'), ('CONDOLENCES', 'CONDOLENCES')], max_length=50, null=True)),
                ('tag', models.ManyToManyField(related_name='tags', to='ecard.card')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='ecard.card')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=100)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecard.card')),
                ('commentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
