# Generated by Django 4.1.3 on 2022-11-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0002_card_user_bio_user_name_tag_friend_favorite_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border_color',
            field=models.CharField(choices=[('YELLOW', 'YELLOW'), ('BLACK', 'BLACK'), ('WHITE', 'WHITE'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('PURPLE', 'PURPLE'), ('ORANGE', 'ORANGE')], default='BLACK', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='border_style',
            field=models.CharField(choices=[('SOLID', 'SOLID'), ('DOUBLE', 'DOUBLE'), ('GROOVE', 'GROOVE'), ('DOTTED', 'DOTTED')], default='SOLID', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('YELLOW', 'YELLOW'), ('BLACK', 'BLACK'), ('WHITE', 'WHITE'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('PURPLE', 'PURPLE'), ('ORANGE', 'ORANGE')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(choices=[('YELLOW', 'YELLOW'), ('BLACK', 'BLACK'), ('WHITE', 'WHITE'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('PURPLE', 'PURPLE'), ('ORANGE', 'ORANGE')], default='BLACK', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_family',
            field=models.CharField(choices=[('ARIAL', 'ARIAL'), ('UBUNTO', 'UBUNTO'), ('RALEWAY', 'RALEWAY'), ('MERRIWEATHER', 'MERRIWEATHER')], default='UBUNTO', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_alignment',
            field=models.CharField(choices=[('LEFT', 'LEFT'), ('RIGHT', 'RIGHT'), ('CENTER', 'CENTER')], default='LEFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(blank=True, choices=[('VALENTINES-DAY', 'VALENTINES-DAY'), ('WEDDING', 'WEDDING'), ('BIRTHDAY', 'BIRTHDAY'), ('THANK-YOU', 'THANK-YOU'), ('CONDOLENCES', 'CONDOLENCES'), ('CHRISTMAS', 'CHRISTMAS')], max_length=50, null=True),
        ),
    ]
