# Generated by Django 4.1.3 on 2022-11-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0003_alter_card_border_color_alter_card_border_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border_color',
            field=models.CharField(choices=[('ORANGE', 'ORANGE'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('PURPLE', 'PURPLE'), ('BLACK', 'BLACK'), ('RED', 'RED'), ('YELLOW', 'YELLOW'), ('WHITE', 'WHITE')], default='BLACK', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='border_style',
            field=models.CharField(choices=[('GROOVE', 'GROOVE'), ('DOTTED', 'DOTTED'), ('SOLID', 'SOLID'), ('DOUBLE', 'DOUBLE')], default='SOLID', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('ORANGE', 'ORANGE'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('PURPLE', 'PURPLE'), ('BLACK', 'BLACK'), ('RED', 'RED'), ('YELLOW', 'YELLOW'), ('WHITE', 'WHITE')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(choices=[('ORANGE', 'ORANGE'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('PURPLE', 'PURPLE'), ('BLACK', 'BLACK'), ('RED', 'RED'), ('YELLOW', 'YELLOW'), ('WHITE', 'WHITE')], default='BLACK', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_family',
            field=models.CharField(choices=[('UBUNTO', 'UBUNTO'), ('ARIAL', 'ARIAL'), ('MERRIWEATHER', 'MERRIWEATHER'), ('RALEWAY', 'RALEWAY')], default='UBUNTO', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_alignment',
            field=models.CharField(choices=[('CENTER', 'CENTER'), ('LEFT', 'LEFT'), ('RIGHT', 'RIGHT')], default='LEFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(blank=True, choices=[('CONDOLENCES', 'CONDOLENCES'), ('WEDDING', 'WEDDING'), ('CHRISTMAS', 'CHRISTMAS'), ('BIRTHDAY', 'BIRTHDAY'), ('VALENTINES-DAY', 'VALENTINES-DAY'), ('THANK-YOU', 'THANK-YOU')], max_length=50, null=True),
        ),
    ]
