# Generated by Django 4.1.3 on 2022-11-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0004_alter_card_border_color_alter_card_border_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border_color',
            field=models.CharField(choices=[('WHITE', 'WHITE'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('BLACK', 'BLACK'), ('GREEN', 'GREEN'), ('PURPLE', 'PURPLE'), ('YELLOW', 'YELLOW'), ('ORANGE', 'ORANGE')], default='BLACK', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='border_style',
            field=models.CharField(choices=[('DOTTED', 'DOTTED'), ('GROOVE', 'GROOVE'), ('SOLID', 'SOLID'), ('DOUBLE', 'DOUBLE')], default='SOLID', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('WHITE', 'WHITE'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('BLACK', 'BLACK'), ('GREEN', 'GREEN'), ('PURPLE', 'PURPLE'), ('YELLOW', 'YELLOW'), ('ORANGE', 'ORANGE')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(choices=[('WHITE', 'WHITE'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('BLACK', 'BLACK'), ('GREEN', 'GREEN'), ('PURPLE', 'PURPLE'), ('YELLOW', 'YELLOW'), ('ORANGE', 'ORANGE')], default='BLACK', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_family',
            field=models.CharField(choices=[('RALEWAY', 'RALEWAY'), ('MERRIWEATHER', 'MERRIWEATHER'), ('UBUNTO', 'UBUNTO'), ('ARIAL', 'ARIAL')], default='UBUNTO', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_alignment',
            field=models.CharField(choices=[('LEFT', 'LEFT'), ('CENTER', 'CENTER'), ('RIGHT', 'RIGHT')], default='LEFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(blank=True, choices=[('VALENTINES-DAY', 'VALENTINES-DAY'), ('CHRISTMAS', 'CHRISTMAS'), ('BIRTHDAY', 'BIRTHDAY'), ('CONDOLENCES', 'CONDOLENCES'), ('THANK-YOU', 'THANK-YOU'), ('WEDDING', 'WEDDING')], max_length=50, null=True),
        ),
    ]
