# Generated by Django 4.1.3 on 2022-11-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0006_alter_card_border_color_alter_card_border_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border_color',
            field=models.CharField(choices=[('YELLOW', 'YELLOW'), ('WHITE', 'WHITE'), ('BLACK', 'BLACK'), ('PURPLE', 'PURPLE'), ('RED', 'RED'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('ORANGE', 'ORANGE')], default='BLACK', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='border_style',
            field=models.CharField(choices=[('SOLID', 'SOLID'), ('DOTTED', 'DOTTED'), ('GROOVE', 'GROOVE'), ('DOUBLE', 'DOUBLE')], default='SOLID', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('YELLOW', 'YELLOW'), ('WHITE', 'WHITE'), ('BLACK', 'BLACK'), ('PURPLE', 'PURPLE'), ('RED', 'RED'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('ORANGE', 'ORANGE')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(choices=[('YELLOW', 'YELLOW'), ('WHITE', 'WHITE'), ('BLACK', 'BLACK'), ('PURPLE', 'PURPLE'), ('RED', 'RED'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('ORANGE', 'ORANGE')], default='BLACK', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_family',
            field=models.CharField(choices=[('MERRIWEATHER', 'MERRIWEATHER'), ('ARIAL', 'ARIAL'), ('UBUNTO', 'UBUNTO'), ('RALEWAY', 'RALEWAY')], default='UBUNTO', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_alignment',
            field=models.CharField(choices=[('RIGHT', 'RIGHT'), ('CENTER', 'CENTER'), ('LEFT', 'LEFT')], default='LEFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(blank=True, choices=[('WEDDING', 'WEDDING'), ('THANK-YOU', 'THANK-YOU'), ('CHRISTMAS', 'CHRISTMAS'), ('VALENTINES-DAY', 'VALENTINES-DAY'), ('CONDOLENCES', 'CONDOLENCES'), ('BIRTHDAY', 'BIRTHDAY')], max_length=50, null=True),
        ),
    ]
