# Generated by Django 4.1.3 on 2022-11-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0009_alter_card_text_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='font_family',
            field=models.CharField(choices=[('UBUNTO', 'UBUNTO'), ('ARIAL', 'ARIAL'), ('MERRIWEATHER', 'MERRIWEATHER'), ('RALEWAY', 'RALEWAY')], default='UBUNTO', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_alignment',
            field=models.CharField(choices=[('CENTER', 'CENTER'), ('LEFT', 'LEFT'), ('RIGHT', 'RIGHT')], default='LEFT', max_length=50),
        ),
    ]
