# Generated by Django 4.1.3 on 2022-11-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0011_alter_card_border_style_alter_card_font_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border_style',
            field=models.CharField(choices=[('SOLID', 'SOLID'), ('DOTTED', 'DOTTED'), ('DOUBLE', 'DOUBLE'), ('GROOVE', 'GROOVE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_family',
            field=models.CharField(choices=[('RALEWAY', 'RALEWAY'), ('ARIAL', 'ARIAL'), ('MERRIWEATHER', 'MERRIWEATHER'), ('UBUNTO', 'UBUNTO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_alignment',
            field=models.CharField(choices=[('CENTER', 'CENTER'), ('LEFT', 'LEFT'), ('RIGHT', 'RIGHT')], max_length=50),
        ),
    ]
