# Generated by Django 4.1.3 on 2022-11-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0012_alter_card_border_style_alter_card_font_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border_style',
            field=models.CharField(choices=[('SOLID', 'SOLID'), ('DOTTED', 'DOTTED'), ('GROOVE', 'GROOVE'), ('DOUBLE', 'DOUBLE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_family',
            field=models.CharField(choices=[('RALEWAY', 'RALEWAY'), ('ARIAL', 'ARIAL'), ('UBUNTO', 'UBUNTO'), ('MERRIWEATHER', 'MERRIWEATHER')], max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_alignment',
            field=models.CharField(choices=[('LEFT', 'LEFT'), ('CENTER', 'CENTER'), ('RIGHT', 'RIGHT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(blank=True, choices=[('VALENTINES-DAY', 'VALENTINES-DAY'), ('CONDOLENCES', 'CONDOLENCES'), ('THANK-YOU', 'THANK-YOU'), ('BIRTHDAY', 'BIRTHDAY'), ('WEDDING', 'WEDDING'), ('CHRISTMAS', 'CHRISTMAS')], max_length=50, null=True),
        ),
    ]
