# Generated by Django 4.1.3 on 2022-11-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0015_alter_card_options_alter_card_border_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border_color',
            field=models.CharField(choices=[('WHITE', 'WHITE'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('RED', 'RED'), ('YELLOW', 'YELLOW'), ('PURPLE', 'PURPLE'), ('ORANGE', 'ORANGE'), ('BLACK', 'BLACK')], default='BLACK', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='border_style',
            field=models.CharField(choices=[('SOLID', 'SOLID'), ('GROOVE', 'GROOVE'), ('DOTTED', 'DOTTED'), ('DOUBLE', 'DOUBLE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('WHITE', 'WHITE'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('RED', 'RED'), ('YELLOW', 'YELLOW'), ('PURPLE', 'PURPLE'), ('ORANGE', 'ORANGE'), ('BLACK', 'BLACK')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(choices=[('WHITE', 'WHITE'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('RED', 'RED'), ('YELLOW', 'YELLOW'), ('PURPLE', 'PURPLE'), ('ORANGE', 'ORANGE'), ('BLACK', 'BLACK')], default='BLACK', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_family',
            field=models.CharField(choices=[('MERRIWEATHER', 'MERRIWEATHER'), ('ARIAL', 'ARIAL'), ('RALEWAY', 'RALEWAY'), ('UBUNTO', 'UBUNTO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_alignment',
            field=models.CharField(choices=[('LEFT', 'LEFT'), ('CENTER', 'CENTER'), ('RIGHT', 'RIGHT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(blank=True, choices=[('THANK-YOU', 'THANK-YOU'), ('CONDOLENCES', 'CONDOLENCES'), ('CHRISTMAS', 'CHRISTMAS'), ('VALENTINES-DAY', 'VALENTINES-DAY'), ('WEDDING', 'WEDDING'), ('BIRTHDAY', 'BIRTHDAY')], max_length=50, null=True),
        ),
    ]
