# Generated by Django 4.1.3 on 2022-11-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0016_alter_card_border_color_alter_card_border_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border_color',
            field=models.CharField(choices=[('WHITE', 'WHITE'), ('RED', 'RED'), ('ORANGE', 'ORANGE'), ('YELLOW', 'YELLOW'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('PURPLE', 'PURPLE'), ('BLACK', 'BLACK')], default='BLACK', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='border_style',
            field=models.CharField(choices=[('SOLID', 'SOLID'), ('DOTTED', 'DOTTED'), ('DOUBLE', 'DOUBLE'), ('GROOVE', 'GROOVE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('WHITE', 'WHITE'), ('RED', 'RED'), ('ORANGE', 'ORANGE'), ('YELLOW', 'YELLOW'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('PURPLE', 'PURPLE'), ('BLACK', 'BLACK')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(choices=[('WHITE', 'WHITE'), ('RED', 'RED'), ('ORANGE', 'ORANGE'), ('YELLOW', 'YELLOW'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('PURPLE', 'PURPLE'), ('BLACK', 'BLACK')], default='BLACK', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_family',
            field=models.CharField(choices=[('UBUNTO', 'UBUNTO'), ('ARIAL', 'ARIAL'), ('MERRIWEATHER', 'MERRIWEATHER'), ('RALEWAY', 'RALEWAY')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(blank=True, choices=[('BIRTHDAY', 'BIRTHDAY'), ('CHRISTMAS', 'CHRISTMAS'), ('WEDDING', 'WEDDING'), ('VALENTINES-DAY', 'VALENTINES-DAY'), ('THANK-YOU', 'THANK-YOU'), ('CONDOLENCES', 'CONDOLENCES')], max_length=50, null=True),
        ),
    ]
