# Generated by Django 4.1.3 on 2022-11-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0017_alter_card_border_color_alter_card_border_style_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('type',), name='Unique_tag'),
        ),
    ]
