# Generated by Django 4.1.3 on 2022-11-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0018_tag_unique_tag'),
        ('ecard', '0019_alter_friend_user'),
    ]

    operations = [
    ]
