# Generated by Django 4.1.3 on 2022-11-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0021_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='color',
            new_name='background_color',
        ),
    ]
