# Generated by Django 4.1.3 on 2022-11-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0028_remove_friend_user_friend_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='Friendship',
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('current_user', 'friend'), name='unique_friendship'),
        ),
    ]
