# Generated by Django 4.1.3 on 2022-11-28 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0028_friendship_delete_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friend',
        ),
        migrations.AddField(
            model_name='friendship',
            name='friend',
            field=models.ManyToManyField(related_name='friendships', to=settings.AUTH_USER_MODEL),
        ),
    ]
