# Generated by Django 4.1.3 on 2022-11-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0029_rename_friend_friendship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ecard.card'),
        ),
    ]
