# Generated by Django 4.1.3 on 2022-11-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0030_alter_comment_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='border_color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='border_style',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_family',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_alignment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
