# Generated by Django 4.1.3 on 2022-11-30 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0031_alter_card_background_color_alter_card_border_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['created_at']},
        ),
    ]
